In [1]:
import sys
sys.path.append('..')
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sympy import simplify_logic

from lens.utils.relu_nn import get_reduced_model, prune_features
from lens import logic
from lens.utils.base import collect_parameters

torch.manual_seed(0)
np.random.seed(0)

In [2]:
gene_expression_matrix = pd.read_csv('w_1/data_0.csv', index_col=None, header=None)
labels = pd.read_csv('w_1/tempLabels_W-1.csv', index_col=None, header=None)

In [3]:
gene_expression_matrix

,0,1,2,3,4,5,6,7,8,9,...,28392,28393,28394,28395,28396,28397,28398,28399,28400,28401
0,14.622486,11.162004,3.320000,3.320000,3.320000,12.788433,6.143456,3.320000,4.876620,3.320000,...,3.32,3.320000,3.885589,3.914260,3.320000,3.32,3.320000,4.465420,3.320000,4.973620
1,14.398743,11.000080,3.320000,3.320000,3.320000,12.845914,6.147482,3.320000,4.484223,3.320000,...,3.32,3.575025,4.236519,4.047825,3.320000,3.32,4.176269,3.320000,4.553796,4.967418
2,14.692079,11.100175,3.320000,4.171535,3.320000,12.712544,5.583210,3.320000,3.478171,3.320000,...,3.32,3.320000,3.992331,4.865538,3.320000,3.32,3.488281,3.406285,3.320000,6.676063
3,14.613382,11.023209,3.320000,3.320000,3.320000,12.750496,5.688023,3.320000,4.464426,3.320000,...,3.32,3.855643,3.320000,4.905350,3.320000,3.32,4.158393,4.433457,3.874214,5.981160
4,14.482065,10.989851,3.320000,3.992726,4.574745,12.878702,6.195418,4.177962,3.872567,3.320000,...,3.32,3.320000,3.320000,4.879493,3.320000,3.32,4.571869,3.320000,4.982136,6.145585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,14.565031,11.699843,3.320000,3.320000,3.320000,12.789212,6.504027,3.320000,3.320000,6.182912,...,3.32,3.320000,3.320000,4.338456,3.771718,3.32,3.320000,3.320000,3.320000,6.100644
57,14.624502,11.918757,3.320000,4.292406,3.430485,10.728709,6.197159,3.320000,4.089918,5.201608,...,3.32,3.320000,3.320000,4.790134,3.320000,3.32,4.985474,4.444057,3.580523,6.301926
58,14.585190,11.090112,3.320000,3.674768,3.320000,12.877485,6.326960,3.320000,3.320000,3.320000,...,3.32,3.320000,3.320000,4.547342,3.320000,3.32,4.064473,3.320000,4.254152,5.964505
59,14.449554,10.805855,3.320000,3.320000,3.320000,12.660038,6.261395,3.320000,4.125096,3.320000,...,3.32,3.784260,3.644823,4.546974,3.427441,3.32,4.666265,3.888525,3.765754,5.452018
60,14.439020,11.080826,4.152651,3.320000,3.320000,12.187504,6.154358,3.320000,4.247009,3.320000,...,3.32,3.671102,3.519157,4.771458,3.320000,3.32,5.115644,3.320000,3.410361,6.449961

In [4]:
labels

                                         0
0               diagnosis: healthy control
1               diagnosis: healthy control
2               diagnosis: healthy control
3               diagnosis: healthy control
4               diagnosis: healthy control
..                                     ...
56  omalizumab responder status: Responder
57  omalizumab responder status: Responder
58  omalizumab responder status: Responder
59  omalizumab responder status: Responder
60  omalizumab responder status: Responder

[61 rows x 1 columns]

In [5]:
encoder = LabelEncoder()
labels_encoded = encoder.fit_transform(labels.values)
labels_encoded_noncontrols = labels_encoded[labels_encoded!=0] - 1

data_controls = gene_expression_matrix[labels_encoded==0]
data = gene_expression_matrix[labels_encoded!=0]

gene_signature = data_controls.mean(axis=0)
data_scaled = data - gene_signature

scaler = MinMaxScaler((0, 1))
scaler.fit(data_scaled)
data_normalized = scaler.transform(data_scaled)

x_train = torch.FloatTensor(data_normalized)
y_train = torch.FloatTensor(labels_encoded_noncontrols).unsqueeze(1)
print(x_train.shape)
print(y_train.shape)

/home/pietro/anaconda3/envs/dev/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

torch.Size([40, 28402])
torch.Size([40, 1])

In [11]:
layers = [
    torch.nn.Linear(x_train.size(1), 10),
    torch.nn.ReLU(),
    torch.nn.Linear(10, 5),
    torch.nn.ReLU(),
    torch.nn.Linear(5, 1),
    torch.nn.Sigmoid(),
]
model = torch.nn.Sequential(*layers)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
model.train()
need_pruning = True
for epoch in range(13000):
    # forward pass
    optimizer.zero_grad()
    y_pred = model(x_train)
    # Compute Loss
    loss = torch.nn.functional.mse_loss(y_pred, y_train)

    for module in model.children():
        if isinstance(module, torch.nn.Linear):
            loss += 0.007 * torch.norm(module.weight, 1)

    # backward pass
    loss.backward()
    optimizer.step()

    # compute accuracy
    if epoch % 1000 == 0:
        y_pred_d = (y_pred > 0.5)
        accuracy = (y_pred_d.eq(y_train).sum(dim=1) == y_train.size(1)).sum().item() / y_train.size(0)
        print(f'Epoch {epoch}: train accuracy: {accuracy:.4f}')
        
    if epoch > 5000 and need_pruning:
        prune_features(model)
        need_pruning = False

Epoch 0: train accuracy: 0.7500
Epoch 1000: train accuracy: 0.7500
Epoch 2000: train accuracy: 0.7500
Epoch 3000: train accuracy: 0.7500
Epoch 4000: train accuracy: 0.9750
Epoch 5000: train accuracy: 1.0000
Epoch 6000: train accuracy: 0.8500
Epoch 7000: train accuracy: 0.9500
Epoch 8000: train accuracy: 0.9750
Epoch 9000: train accuracy: 0.9750
Epoch 10000: train accuracy: 1.0000
Epoch 11000: train accuracy: 1.0000
Epoch 12000: train accuracy: 1.0000

# Combine local explanations

In [12]:
global_explanation, predictions, counter = logic.combine_local_explanations(model, x_train, y_train, 
                                                                          topk_explanations=3)

ynp = y_train.detach().numpy()[:, 0]
accuracy = np.sum(predictions == ynp) / len(ynp)
print(f'Accuracy of when using the formula "{global_explanation}": {accuracy:.4f}')

Accuracy of when using the formula "(feature0000006749 & feature0000026329) | (feature0000010382 & feature0000013710 & feature0000021119 & feature0000025379 & feature0000026329 & feature0000027097 & ~feature0000013464) | (feature0000010382 & feature0000021119 & feature0000026329 & ~feature0000013464 & ~feature0000013710 & ~feature0000025379 & ~feature0000027097)": 0.5500

In [8]:
w, b = collect_parameters(model)
feature_weights = w[0]
feature_used_bool = np.sum(np.abs(feature_weights), axis=0) > 0
feature_used = np.nonzero(feature_used_bool)[0]
len(feature_used)

10

In [9]:
counter

Counter({'~feature0000003625 & feature0000005394 & ~feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & feature0000022371 & ~feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & ~feature0000022371 & feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & feature0000022371 & ~feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & ~feature0000021119 & ~feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         'feature0000003625 & ~feature0000005394 & feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & ~feature0000021119 & ~feature0000022371 & feature0000025379 & feature0000026329': 1,
         'feature0000003625 & ~feature0000005394 & feature0000006749 & ~feature0000010382 & feature0000013464 & feature0000013710 & ~feature0000021119 & ~feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         'feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & ~feature0000022371 & feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000005394 & feature0000006749 & ~feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & feature0000022371 & feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & feature0000005394 & feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & ~feature0000021119 & ~feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         '~feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & ~feature0000021119 & ~feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & ~feature0000021119 & feature0000022371 & ~feature0000025379 & ~feature0000026329': 1,
         'feature0000013710 & feature0000022371 & feature0000025379': 1,
         '~feature0000003625 & ~feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & feature0000022371 & feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & ~feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & feature0000022371 & feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 2,
         '~feature0000003625 & ~feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & feature0000022371 & feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000005394 & feature0000006749 & ~feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 2,
         'feature0000003625 & ~feature0000005394 & ~feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & ~feature0000021119 & feature0000022371 & feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000022371 & feature0000025379': 1,
         'feature0000003625 & ~feature0000005394 & feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & feature0000022371 & ~feature0000025379 & feature0000026329': 1,
         '~feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 2,
         'feature0000003625 & ~feature0000005394 & ~feature0000006749 & ~feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 1,
         'feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & feature0000022371': 1,
         '~feature0000003625 & feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & feature0000013710 & ~feature0000021119 & ~feature0000022371 & feature0000025379 & ~feature0000026329': 1,
         '~feature0000003625 & ~feature0000005394 & ~feature0000006749 & feature0000010382 & ~feature0000013464 & ~feature0000013710 & feature0000021119 & ~feature0000022371 & ~feature0000025379 & feature0000026329': 1})

In [10]:
pd.DataFrame({
    'predictions': predictions.ravel(),
    'labels': y_train.detach().numpy().ravel(),
})

    predictions  labels
0         False     0.0
1         False     0.0
2         False     0.0
3         False     0.0
4         False     0.0
5         False     0.0
6         False     0.0
7         False     0.0
8         False     0.0
9         False     0.0
10         True     1.0
11         True     1.0
12         True     1.0
13         True     1.0
14         True     1.0
15         True     1.0
16         True     1.0
17         True     1.0
18         True     1.0
19         True     1.0
20         True     1.0
21         True     1.0
22         True     1.0
23         True     1.0
24         True     1.0
25         True     1.0
26         True     1.0
27         True     1.0
28         True     1.0
29         True     1.0
30         True     1.0
31         True     1.0
32         True     1.0
33         True     1.0
34         True     1.0
35         True     1.0
36         True     1.0
37         True     1.0
38         True     1.0
39         True     1.0